[project]
name = "reportero"
version = "0.1.0"
description = "Reportero is a tool to create reports on pdf"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "coverage>=7.6.12",
    "pytest>=8.3.4",
]
